name: biust_revision_app_backend
description: A backend server for the BIUST Revision App
version: 0.0.1
environment:
    sdk: ">=2.12.0 <3.0.0"

dependencies:
    shelf: ^1.4.1
    shelf_router: ^1.1.4
    shelf_static: ^1.1.2
